console.log("Hello World")

console.log(document.body)
let cont = document.body.childNodes[1]
console.log(cont.firstChild)
console.log(cont.lastChild)
console.log(cont.firstElementChild)
console.log(cont.lastElementChild)
console.log(cont.lastElementChild.style.color = 'red')
console.log(cont.lastElementChild.style.background = 'pink')
console.log(cont.lastElementChild.parentElement)
console.log(document.body.firstElementChild.childNodes)
console.log(document.body.firstElementChild)              // first element
document.body.firstElementChild.childNodes  //all child nodes
console.log(document.body.firstElementChild.children)    //only html elements
console.log(document.body.firstElementChild.children[1])
console.log(document.body.firstElementChild.children[1].nextElementSibling)
console.log(document.body.firstElementChild.children[1].previousElementSibling)
console.log(document.body.firstElementChild.children[1].previousSibling)
console.log(document.body.children)
console.log(document.body.children[1])
console.log(document.body.children[1].rows)
console.log(document.body.children[1].caption)
console.log(document.body.children[1].tHead)
console.log(document.body.children[1].tBodies)
console.log(document.body.children[1].children[1].rows)
console.log(document.body.children[1].children[1].children[0].cells)
console.log(document.body.children[1].children[1].children[0].sectionRowIndex)
console.log(document.body.children[1].children[1].children[0].rowIndex)
console.log(document.body.children[1].children[1].children[0].children[0].cellIndex)
